name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -project FeedReader.xcodeproj -scheme "FeedReader" -allowProvisioningUpdates
    - name: Run tests
      run: sxcodebuild clean test -project FeedReader.xcodeproj -scheme "FeedReader" -allowProvisioningUpdates
